// Static parts catalog — imported directly so the browser never needs a fetch
// for the similarity engine.  The useJSON hook is still used in UI pages that
// want loading/error states.

export type Part = {
  sku: string;
  name: string;
  family: string;
  material: string;
  supplier_tier: string;
  supplier: string;
  plants: string[];
  lines: string[];
  defect_modes: string[];
  bom_neighbors: string[];
};

// Raw catalog embedded at build time so related.ts can run synchronously.
// Mirror of /public/data/parts.json — keep in sync with gen_data output.
export const PARTS: Part[] = [
  {
    sku: 'BC-4401',
    name: 'Caliper Body — Compact',
    family: 'Brake caliper',
    material: 'Gray cast iron',
    supplier_tier: 'Tier-1',
    supplier: 'Intermet Corp',
    plants: ['TOL', 'IND'],
    lines: ['TOL-L1', 'TOL-L2', 'IND-L1'],
    defect_modes: ['Bore diameter +.002in', 'Surface finish — pitting'],
    bom_neighbors: ['BC-4402', 'BC-4403', 'BA-5501'],
  },
  {
    sku: 'BC-4402',
    name: 'Caliper Body — HD Truck',
    family: 'Brake caliper',
    material: 'Ductile iron',
    supplier_tier: 'Tier-1',
    supplier: 'Intermet Corp',
    plants: ['IND'],
    lines: ['IND-L1'],
    defect_modes: ['Bore diameter +.002in'],
    bom_neighbors: ['BC-4401', 'BC-4403', 'BA-5503'],
  },
  {
    sku: 'BC-4403',
    name: 'Caliper Bracket',
    family: 'Brake caliper',
    material: 'Gray cast iron',
    supplier_tier: 'Tier-2',
    supplier: 'Grede Holdings',
    plants: ['TOL'],
    lines: ['TOL-L1'],
    defect_modes: ['Bore diameter +.002in', 'Surface finish — pitting'],
    bom_neighbors: ['BC-4401', 'BC-4402', 'BR-3301'],
  },
  {
    sku: 'BC-4404',
    name: 'Caliper Piston — Aluminum',
    family: 'Brake caliper',
    material: 'Aluminum alloy 6061',
    supplier_tier: 'Tier-1',
    supplier: 'Nemak',
    plants: ['TOL', 'IND'],
    lines: ['TOL-L2', 'IND-L1'],
    defect_modes: ['Surface finish — pitting'],
    bom_neighbors: ['BC-4401', 'BC-4402', 'BA-5501'],
  },
  {
    sku: 'BR-3301',
    name: 'Rotor — Ventilated',
    family: 'Brake rotor',
    material: 'Gray cast iron',
    supplier_tier: 'Tier-1',
    supplier: 'Grede Holdings',
    plants: ['TOL'],
    lines: ['TOL-L3', 'TOL-L4'],
    defect_modes: ['Surface finish — pitting'],
    bom_neighbors: ['BR-3302', 'BA-5501', 'BA-5502'],
  },
  {
    sku: 'BR-3302',
    name: 'Rotor — Solid Rear',
    family: 'Brake rotor',
    material: 'Gray cast iron',
    supplier_tier: 'Tier-1',
    supplier: 'Grede Holdings',
    plants: ['TOL'],
    lines: ['TOL-L3', 'TOL-L6'],
    defect_modes: ['Surface finish — pitting', 'Bore diameter +.002in'],
    bom_neighbors: ['BR-3301', 'BA-5501'],
  },
  {
    sku: 'BR-3303',
    name: 'Rotor — Cross-Drilled',
    family: 'Brake rotor',
    material: 'Gray cast iron',
    supplier_tier: 'Tier-2',
    supplier: 'Citation Corp',
    plants: ['TOL'],
    lines: ['TOL-L3', 'TOL-L6'],
    defect_modes: ['Surface finish — pitting'],
    bom_neighbors: ['BR-3301', 'BR-3302'],
  },
  {
    sku: 'BA-5501',
    name: 'Brake Assembly — LV Compact',
    family: 'Brake assembly',
    material: 'Multi-component',
    supplier_tier: 'Tier-1',
    supplier: 'Mercer Integration',
    plants: ['TOL', 'IND'],
    lines: ['TOL-L5', 'IND-L4'],
    defect_modes: ['Bore diameter +.002in', 'Surface finish — pitting'],
    bom_neighbors: ['BC-4401', 'BR-3301', 'BA-5502', 'WH-7701'],
  },
  {
    sku: 'BA-5502',
    name: 'Brake Assembly — Midsize SUV',
    family: 'Brake assembly',
    material: 'Multi-component',
    supplier_tier: 'Tier-1',
    supplier: 'Mercer Integration',
    plants: ['TOL'],
    lines: ['TOL-L5'],
    defect_modes: ['Bore diameter +.002in'],
    bom_neighbors: ['BC-4401', 'BR-3301', 'BA-5501', 'BA-5503'],
  },
  {
    sku: 'BA-5503',
    name: 'Brake Module — LV Truck',
    family: 'Brake assembly',
    material: 'Multi-component',
    supplier_tier: 'Tier-1',
    supplier: 'Mercer Integration',
    plants: ['IND'],
    lines: ['IND-L4', 'IND-L5'],
    defect_modes: ['Bore diameter +.002in', 'Connector seat — partial'],
    bom_neighbors: ['BC-4402', 'BR-3302', 'WH-7703'],
  },
  {
    sku: 'WH-7701',
    name: 'Wire Harness — Body PV',
    family: 'Wire harness PV',
    material: 'Copper wire / PVC insulation',
    supplier_tier: 'Tier-1',
    supplier: 'Aptiv',
    plants: ['STH', 'IND'],
    lines: ['STH-L1', 'STH-L5', 'STH-L6', 'IND-L3'],
    defect_modes: ['Crimp height out-of-spec', 'Continuity fail (open)'],
    bom_neighbors: ['WH-7702', 'WH-7703', 'BA-5501'],
  },
  {
    sku: 'WH-7702',
    name: 'Wire Harness — Engine PV',
    family: 'Wire harness PV',
    material: 'Copper wire / cross-linked PE insulation',
    supplier_tier: 'Tier-1',
    supplier: 'Aptiv',
    plants: ['STH'],
    lines: ['STH-L2', 'STH-L6'],
    defect_modes: ['Crimp height out-of-spec', 'Connector seat — partial'],
    bom_neighbors: ['WH-7701', 'WH-7703'],
  },
  {
    sku: 'WH-7703',
    name: 'Wire Harness — Instrument Panel LV Truck',
    family: 'Wire harness PV',
    material: 'Copper wire / PVC insulation',
    supplier_tier: 'Tier-1',
    supplier: 'Lear Corp',
    plants: ['STH', 'IND'],
    lines: ['STH-L3', 'STH-L8', 'IND-L3'],
    defect_modes: ['Crimp height out-of-spec', 'Continuity fail (open)', 'Connector seat — partial'],
    bom_neighbors: ['WH-7701', 'WH-7702', 'BA-5503'],
  },
  {
    sku: 'WH-7704',
    name: 'Wire Harness — Door Module',
    family: 'Wire harness PV',
    material: 'Copper wire / PVC insulation',
    supplier_tier: 'Tier-2',
    supplier: 'Lear Corp',
    plants: ['STH'],
    lines: ['STH-L7', 'STH-L8'],
    defect_modes: ['Crimp height out-of-spec'],
    bom_neighbors: ['WH-7701', 'WH-7702', 'WP-8801'],
  },
  {
    sku: 'WP-8801',
    name: 'Wire Prep — 0.35mm PV Ground',
    family: 'Wire prep',
    material: 'Copper wire / PVC insulation',
    supplier_tier: 'Tier-2',
    supplier: 'Leoni Wire',
    plants: ['STH'],
    lines: ['STH-L4'],
    defect_modes: ['Crimp height out-of-spec'],
    bom_neighbors: ['WP-8802', 'WH-7701', 'WH-7704'],
  },
  {
    sku: 'WP-8802',
    name: 'Wire Prep — 0.5mm Signal',
    family: 'Wire prep',
    material: 'Copper wire / cross-linked PE insulation',
    supplier_tier: 'Tier-2',
    supplier: 'Leoni Wire',
    plants: ['STH'],
    lines: ['STH-L4'],
    defect_modes: ['Crimp height out-of-spec', 'Continuity fail (open)'],
    bom_neighbors: ['WP-8801', 'WH-7702', 'WH-7703'],
  },
  {
    sku: 'WP-8803',
    name: 'Wire Prep — 2.0mm Power',
    family: 'Wire prep',
    material: 'Copper wire / XLPE insulation',
    supplier_tier: 'Tier-2',
    supplier: 'Leoni Wire',
    plants: ['STH'],
    lines: ['STH-L4'],
    defect_modes: ['Continuity fail (open)'],
    bom_neighbors: ['WP-8801', 'WP-8802', 'WH-7703'],
  },
];

export function partBySku(sku: string): Part | undefined {
  return PARTS.find((p) => p.sku === sku);
}
